/* Feminine Strength Co. — reusable client architecture demo
   Aliyah is seeded as a client configuration. The UI is data-driven so the same shell can render another client later. */
const CFG=window.FSC_CONFIG||{};
const hasSupabase=!!(CFG.SUPABASE_URL&&CFG.SUPABASE_PUBLISHABLE_KEY&&window.supabase);
const sb=hasSupabase?window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY):null;
const STORE='fsc_master_v1';

const CLIENT={
 id:'demo-aliyah',name:'Aliyah',coach:'Christin',status:'active',programWeeks:12,week:1,
 goals:['Build strength','Consistency','Fuel performance'],
 schedule:{Monday:{type:'independent',focus:'Lower Body'},Tuesday:{type:'coached',focus:'Total Body'},Wednesday:{type:'independent',focus:'Upper Body'},Thursday:{type:'mobility',focus:'Mobility / Pilates'},Friday:{type:'flex',focus:'Mobility or Walk'},Saturday:{type:'walk',focus:'Walk'},Sunday:{type:'rest',focus:'Rest'}},
 checkin:{title:"How's today going?",options:['Good day','Busy day','Horrible day'],items:[['electrolytes','Electrolytes, first thing','before coffee, before anything else'],['trained','Trained today','coached or independent session'],['protein','Hit my protein','close enough counts'],['walk','Got a walk in',"45 min counts, doesn't need to be a session"],['water','Hit my water','8+ cups — already your habit, just protect it']]},
 nutrition:{mode:'awareness',calories:1860,protein:105,carbs:205,fatMin:65,maintenance:true,phaseNote:'No deficit for these first four weeks. Your body needs to know food is steady and safe before we ask anything else of it.',grabGo:['Rotisserie chicken + microwave rice','Greek yogurt + protein granola','Protein shake + banana','Turkey + cheese roll-ups','Cottage cheese + fruit','Hard-boiled eggs (batch-prepped)']},
 progress:{weight:176.8,leanMass:102.8,bodyFat:41.9,bmr:1377,weekLabel:'Week 1 of 12'},
 workouts:[
  {id:'aliyah-lower',day:'Monday',name:'Lower Body',focus:'Independent session',note:'Your lower-body day. Same split repeats each phase while exercises progress.',exercises:[]},
  {id:'aliyah-total',day:'Tuesday',name:'Total Body',focus:'Coached with Christin',note:'Your one coached session. The specific exercise prescription is assigned in Coach Hub.',exercises:[]},
  {id:'aliyah-upper',day:'Wednesday',name:'Upper Body',focus:'Independent session',note:'Upper-body day. The specific exercise prescription is assigned in Coach Hub.',exercises:[]},
  {id:'aliyah-mobility',day:'Thursday',name:'Mobility Flow',focus:'Mobility / Pilates',note:'Same flow every week — hips, t-spine, hamstrings, ankles, then down-regulate. ~20–25 min.',exercises:[]}
],resources:[{name:'Feminine Strength Co. coaching resources',type:'Resource',url:'#'}]
};

let state=loadState();
function loadState(){try{return JSON.parse(localStorage.getItem(STORE))||{checkins:{},nutrition:[],movement:[],wins:[],sets:{},notes:[]}}catch{return{checkins:{},nutrition:[],movement:[],wins:[],sets:{},notes:[]}}}
function persist(){localStorage.setItem(STORE,JSON.stringify(state))}
function today(){return new Date().toISOString().slice(0,10)}
function dayName(){return new Date().toLocaleDateString('en-US',{weekday:'long'})}
function fmtDate(d){return new Date(d+'T12:00:00').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}

function saveCloud(table,payload){if(!sb)return Promise.resolve(false);return sb.from(table).insert(payload).then(({error})=>!error).catch(()=>false)}
async function initAuth(){if(!sb)return;try{const {data}=await sb.auth.getSession();if(data.session) toast('Signed in');}catch(e){console.warn(e)}}

function render(){document.getElementById('app').innerHTML=`<div class="shell"><header class="topbar"><div class="topbar-inner"><div><div class="brand">Feminine Strength Co.</div><div class="name" id="headerName">Hey, ${esc(CLIENT.name)}</div><div class="role">One day at a time. That's the whole plan.</div></div><div class="mode"><button class="active" data-mode="client">Client</button><button data-mode="coach">Coach Hub</button></div></div></header><nav class="nav" id="nav">${['today','training','nutrition','movement','progress','resources'].map((x,i)=>`<button class="${i===0?'active':''}" data-tab="${x}">${label(x)}</button>`).join('')}</nav><main id="main"></main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>showMode(b.dataset.mode));showTab('today');}
function label(x){return({today:'Today',training:'Training',nutrition:'Nutrition',movement:'Movement',progress:'Progress',resources:'Resources'})[x]}
function showTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const main=document.getElementById('main');main.innerHTML=views[tab]();bindCommon();}
function showMode(mode){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));document.getElementById('nav').classList.toggle('hide',mode==='coach');document.getElementById('headerName').textContent=mode==='coach'?'Coach Hub':'Hey, '+CLIENT.name;document.getElementById('main').innerHTML=mode==='coach'?coachView():views.today();if(mode==='client')bindCommon();else bindCoach();}

const views={
today:()=>{const t=today(),d=CLIENT.schedule[dayName()]||CLIENT.schedule.Monday,c=state.checkins[t]||{},done=Object.values(c.items||{}).filter(Boolean).length;return `<div class="grid grid-main"><div class="grid"><section class="hero"><div class="eyebrow">${fmtDate(t)}</div><div class="title">How's today going?</div><div class="sub">Good day, busy day, or horrible day — the plan adapts to you.</div><div class="segment" style="margin-top:15px">${CLIENT.checkin.options.map(o=>`<button class="seg ${c.dayType===o?'active':''}" data-daytype="${esc(o)}">${esc(o)}</button>`).join('')}</div></section><section class="card"><div class="eyebrow">Today's rhythm</div><div class="title">${esc(d.focus)}</div><div class="sub">${d.type==='coached'?'Coached, with Christin':d.type==='independent'?'Independent session':d.type==='mobility'?'Mobility / Pilates':d.type==='walk'?'Walk day':d.type==='rest'?'Rest day':'Your call — mobility or a walk'}</div><div class="day-pills" style="margin-top:13px">${Object.entries(CLIENT.schedule).map(([day,v])=>`<button class="day-pill ${day===dayName()?'today':''}" data-goto-day="${day}"><div class="d">${day.slice(0,3)}</div><div class="f">${esc(v.focus)}</div></button>`).join('')}</div></section><section class="card"><div class="eyebrow">Daily check-in</div><div class="title">Protect the basics</div><div class="check-grid">${CLIENT.checkin.items.map(([k,a,b])=>`<label class="check ${(c.items||{})[k]?'done':''}"><input type="checkbox" data-check="${k}" ${(c.items||{})[k]?'checked':''}><span>${esc(a)}<em>${esc(b)}</em></span></label>`).join('')}</div><div class="field"><label>Anything to flag for Christin?</label><textarea class="input textarea" id="flag" placeholder="Optional"></textarea></div><button class="btn" id="saveCheck">Save today's check-in</button></section></div><aside class="grid"><section class="card"><div class="eyebrow">Your coach</div><div class="coach-client"><div class="avatar">C</div><div><div style="font-weight:700;font-size:13px">Christin</div><div class="sub">Feminine Strength Co.</div></div></div><p class="quote" style="margin-top:15px">One good day stacks on another. Let the plan meet you where you are.</p></section><section class="card"><div class="eyebrow">This week</div><div class="grid three" style="margin-top:10px"><div class="stat"><div class="n">${countSessions()}</div><div class="l">Sessions</div></div><div class="stat"><div class="n">${Object.keys(state.checkins).length}</div><div class="l">Check-ins</div></div><div class="stat"><div class="n">${state.wins.length}</div><div class="l">Wins</div></div></div></section></aside></div>`},
training:()=>`<div class="grid">${CLIENT.workouts.map(w=>workoutCard(w)).join('')}</div>`,
nutrition:()=>`<div class="grid grid-main"><section class="grid"><section class="card"><div class="eyebrow">Today's fuel</div><div class="title">Awareness, not a score to hit</div><div class="grid three" style="margin:13px 0"><div class="stat"><div class="n">${nutritionTotals().protein}</div><div class="l">Protein g</div></div><div class="stat"><div class="n">${nutritionTotals().cal}</div><div class="l">Calories</div></div><div class="stat"><div class="n">—</div><div class="l">No grade</div></div></div><div class="sub">Log if it's useful to you. No target to hit, no red or green — just information for you and Christin.</div><div class="field"><label>Meal / food</label><input class="input" id="mealName" placeholder="e.g. chicken + rice"></div><div class="meal" style="margin-top:7px"><input class="input" id="mealProtein" inputmode="decimal" placeholder="protein g"><input class="input" id="mealCal" inputmode="decimal" placeholder="cal"><button class="btn small" id="addMeal">+</button></div><div class="list">${state.nutrition.slice().reverse().map(m=>`<div class="row"><span class="label">${esc(m.name)}</span><span class="value">${m.protein||0}g · ${m.cal||0} cal</span></div>`).join('')||'<div class="empty">Nothing logged yet today.</div>'}</div></section></section><aside class="grid"><section class="card"><div class="eyebrow">Starting point</div><div class="title">Where you're starting</div><div class="grid two" style="margin-top:12px">${[['176.8','Weight (lb)'],['102.8','Lean Mass (lb)'],['41.9%','Body Fat'],['1,377','BMR (kcal)']].map(x=>`<div class="stat"><div class="n">${x[0]}</div><div class="l">${x[1]}</div></div>`).join('')}</div><p class="sub" style="margin-top:12px">A starting photograph, not a verdict. Every number here exists to build a plan that fits you.</p></section><section class="card"><div class="eyebrow">Current approach</div><div class="title">Eating at maintenance</div><div class="list"><div class="row"><span class="label">Daily guide</span><span class="value">~1,860 kcal</span></div><div class="row"><span class="label">Protein priority</span><span class="value">105g/day</span></div><div class="row"><span class="label">Carbs</span><span class="value">~205g/day</span></div><div class="row"><span class="label">Fat minimum</span><span class="value">~65g/day</span></div></div><div class="good" style="margin-top:10px">${esc(CLIENT.nutrition.phaseNote)}</div></section></aside></div>`,
movement:()=>`<div class="grid grid-main"><section class="grid"><section class="card"><div class="eyebrow">Minimum viable day</div><div class="title">Meet the day you're having</div><div class="list"><div class="row"><span class="label">Good day</span><span class="value">Train + meals + recovery</span></div><div class="row"><span class="label">Busy day</span><span class="value">Protein + solid meal + movement</span></div><div class="row"><span class="label">Horrible day</span><span class="value">Eat + hydrate + sleep</span></div></div></section><section class="card"><div class="eyebrow">Movement log</div><div class="title">Walking & cardio</div><div class="field"><label>What did you do?</label><input class="input" id="moveType" placeholder="Walk, rower, cardio..."/></div><div class="meal"><input class="input" id="moveMin" inputmode="decimal" placeholder="minutes"><input class="input" id="moveDist" inputmode="decimal" placeholder="distance"><button class="btn small" id="addMove">+</button></div><div class="list">${state.movement.slice().reverse().map(m=>`<div class="row"><span class="label">${esc(m.type)}</span><span class="value">${m.min||0} min${m.dist?' · '+esc(m.dist):''}</span></div>`).join('')||'<div class="empty">No movement logged yet.</div>'}</div></section></section><aside class="grid"><section class="card"><div class="eyebrow">Weekly rhythm</div><div class="title">Your movement plan</div>${Object.entries(CLIENT.schedule).map(([d,v])=>`<div class="row"><span class="label">${d}</span><span class="value">${esc(v.focus)}</span></div>`).join('')}</section></aside></div>`,
progress:()=>`<div class="grid grid-main"><section class="grid"><section class="card"><div class="eyebrow">How far you've come</div><div class="title">${esc(CLIENT.progress.weekLabel)}</div><div class="grid two" style="margin-top:12px"><div class="stat"><div class="n">${countSessions()}</div><div class="l">Sessions logged</div></div><div class="stat"><div class="n">${Object.keys(state.checkins).length}</div><div class="l">Check-ins</div></div></div></section><section class="card"><div class="eyebrow">Wins worth remembering</div><div class="title">Keep the evidence</div><div class="field"><input class="input" id="winInput" placeholder="Heavier lift, better form, made it through a rough week..."/><button class="btn" id="addWin">Add win</button></div><div class="wins" style="margin-top:10px">${state.wins.slice().reverse().map(w=>`<div class="win">${esc(w.text)} <span style="color:var(--muted);font-size:10px">· ${fmtDate(w.date)}</span></div>`).join('')||'<div class="empty">Your wins will collect here as you go.</div>'}</div></section></section><aside class="grid"><section class="card"><div class="eyebrow">Starting measures</div><div class="title">Your baseline</div><div class="list"><div class="row"><span class="label">Weight</span><span class="value">176.8 lb</span></div><div class="row"><span class="label">Lean mass</span><span class="value">102.8 lb</span></div><div class="row"><span class="label">Body fat</span><span class="value">41.9%</span></div><div class="row"><span class="label">BMR</span><span class="value">1,377 kcal</span></div></div></section><section class="card"><div class="eyebrow">Progress photos</div><div class="title">Private to you + Christin</div><div class="photo-box">Photo uploads are reserved for the authenticated Supabase Storage layer in the master build.</div></section></aside></div>`,
resources:()=>`<div class="grid"><section class="card"><div class="eyebrow">Resources</div><div class="title">Your Feminine Strength library</div><div class="list">${CLIENT.resources.map(r=>`<div class="resource"><div><div class="rname">${esc(r.name)}</div><div class="rtype">${esc(r.type)}</div></div><button class="btn small secondary" data-resource="${esc(r.url)}">Open</button></div>`).join('')}</div></section><section class="card"><div class="eyebrow">Coach notes</div><div class="title">Private coaching space</div><textarea class="input textarea" id="noteInput" placeholder="Add a note for Christin or save a coaching reflection..."></textarea><button class="btn" id="saveNote">Save note</button><div class="list" style="margin-top:10px">${state.notes.slice().reverse().map(n=>`<div class="row"><span class="label">${esc(n.text)}</span><span class="value">${fmtDate(n.date)}</span></div>`).join('')||'<div class="empty">No notes yet.</div>'}</div></section></div>`
};

function workoutCard(w){return `<section class="workout"><div class="workout-head"><div><div class="wf">${esc(w.day)} · ${esc(w.focus)}</div><div class="wname">${esc(w.name)}</div></div><button class="btn small taupe" data-complete-workout="${w.id}">Complete</button></div><div style="padding:11px 16px;background:var(--soft);font-size:11.5px;color:var(--muted)">${esc(w.note)}</div>${w.exercises.length?w.exercises.map(exerciseCard).join(''):`<div class="ex"><div class="empty">Exercise prescriptions will be assigned here from Coach Hub. This template intentionally does not invent Aliyah's exercises.</div></div>`}</section>`}
function exerciseCard(ex){const key=ex.id;const saved=state.sets[key]||[];return `<div class="ex"><div class="ex-top"><div class="ex-name">${esc(ex.name)}</div><div class="dose">${ex.sets} × ${esc(ex.reps)}</div></div><div class="cue">${esc(ex.cue)}</div><div class="ex-tools">${Array.from({length:ex.sets},(_,i)=>`<div class="set-row"><div class="set-no">S${i+1}</div><input data-set-weight="${key}|${i}" inputmode="decimal" placeholder="weight" value="${esc(saved[i]?.weight||'')}"><input data-set-reps="${key}|${i}" inputmode="numeric" placeholder="reps" value="${esc(saved[i]?.reps||'')}"><button class="btn small secondary" data-save-set="${key}|${i}">Save</button></div>`).join('')}${ex.rest?timerHtml(ex.rest):''}${ex.duration?timerHtml(ex.duration):''}${ex.video?`<a class="video" href="${ex.video}" target="_blank" rel="noopener">▶ Watch demo</a>`:''}</div></div>`}
function timerHtml(seconds){const label=seconds>=60?(seconds/60)+' min':seconds+' sec';return `<div class="timer" data-timer="${seconds}"><span>Timer · ${label}</span><b>${fmtTimer(seconds)}</b><button data-timer-start>Start</button><button class="btn small secondary" data-timer-reset>Reset</button></div>`}
function fmtTimer(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}

function bindCommon(){
 document.querySelectorAll('[data-daytype]').forEach(b=>b.onclick=()=>{const t=today();state.checkins[t]=state.checkins[t]||{items:{}};state.checkins[t].dayType=b.dataset.daytype;persist();showTab('today')});
 document.querySelectorAll('[data-check]').forEach(i=>i.onchange=()=>{const t=today();state.checkins[t]=state.checkins[t]||{items:{}};state.checkins[t].items[i.dataset.check]=i.checked;persist()});
 const save=document.getElementById('saveCheck');if(save)save.onclick=()=>{const t=today();state.checkins[t]=state.checkins[t]||{items:{}};state.checkins[t].flag=document.getElementById('flag').value.trim();state.checkins[t].savedAt=new Date().toISOString();persist();saveCloud('checkins',{client_id:CLIENT.id,checkin_date:t,payload:state.checkins[t]});toast('Check-in saved');showTab('today')};
 document.querySelectorAll('[data-save-set]').forEach(b=>b.onclick=()=>{const [key,i]=b.dataset.saveSet.split('|');state.sets[key]=state.sets[key]||[];state.sets[key][i]={weight:document.querySelector(`[data-set-weight="${key}|${i}"]`).value,reps:document.querySelector(`[data-set-reps="${key}|${i}"]`).value};persist();saveCloud('workout_sets',{client_workout_exercise_id:key,set_number:Number(i)+1,actual_weight:state.sets[key][i].weight,actual_reps:state.sets[key][i].reps});toast('Set saved')});
 document.querySelectorAll('[data-complete-workout]').forEach(b=>b.onclick=()=>{const id=b.dataset.completeWorkout;state.notes.push({date:today(),text:`Completed workout: ${CLIENT.workouts.find(w=>w.id===id)?.name||id}`});persist();toast('Workout marked complete')});
 document.querySelectorAll('[data-timer-start]').forEach(b=>{b.onclick=()=>timerStart(b)});document.querySelectorAll('[data-timer-reset]').forEach(b=>b.onclick=()=>timerReset(b));
 const addMeal=document.getElementById('addMeal');if(addMeal)addMeal.onclick=()=>{const name=document.getElementById('mealName').value.trim();if(!name)return;state.nutrition.push({date:today(),name,protein:document.getElementById('mealProtein').value,cal:document.getElementById('mealCal').value});persist();toast('Nutrition logged');showTab('nutrition')};
 const addMove=document.getElementById('addMove');if(addMove)addMove.onclick=()=>{const type=document.getElementById('moveType').value.trim();if(!type)return;state.movement.push({date:today(),type,min:document.getElementById('moveMin').value,dist:document.getElementById('moveDist').value});persist();toast('Movement logged');showTab('movement')};
 const addWin=document.getElementById('addWin');if(addWin)addWin.onclick=()=>{const text=document.getElementById('winInput').value.trim();if(!text)return;state.wins.push({date:today(),text});persist();toast('Win saved');showTab('progress')};
 const saveNote=document.getElementById('saveNote');if(saveNote)saveNote.onclick=()=>{const text=document.getElementById('noteInput').value.trim();if(!text)return;state.notes.push({date:today(),text});persist();toast('Note saved');showTab('resources')};
 document.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>{if(b.dataset.resource&&b.dataset.resource!=='#')window.open(b.dataset.resource,'_blank');else toast('Resource placeholder — connect it in Coach Hub')});
}
function timerStart(btn){const box=btn.closest('[data-timer]');if(box._timer)return;let remaining=Number(box.dataset.timer);const out=box.querySelector('b');btn.textContent='Pause';box._timer=setInterval(()=>{remaining--;out.textContent=fmtTimer(remaining);if(remaining<=0){clearInterval(box._timer);box._timer=null;btn.textContent='Start';out.textContent=fmtTimer(Number(box.dataset.timer));navigator.vibrate?.([200,100,200]);toast('Timer complete')}},1000);btn.onclick=()=>{clearInterval(box._timer);box._timer=null;btn.textContent='Start';timerStart(btn)}}
function timerReset(btn){const box=btn.closest('[data-timer]');clearInterval(box._timer);box._timer=null;box.querySelector('b').textContent=fmtTimer(Number(box.dataset.timer));box.querySelector('[data-timer-start]').textContent='Start';}
function countSessions(){return state.notes.filter(n=>n.text.startsWith('Completed workout:')).length}
function nutritionTotals(){return state.nutrition.reduce((a,m)=>({protein:a.protein+(Number(m.protein)||0),cal:a.cal+(Number(m.cal)||0)}),{protein:0,cal:0})}
function coachView(){return `<div class="grid grid-main"><section class="grid"><section class="hero"><div class="eyebrow">Coach Hub · Client</div><div class="title">${esc(CLIENT.name)}</div><div class="sub">This is the reusable client record rendered from the same platform shell. Programming and tracking are client-specific data.</div><div class="coach-actions"><button class="btn taupe" id="editProgram">Edit programming</button><button class="btn secondary" id="coachNote">Add coach note</button></div></section><section class="card"><div class="eyebrow">Today's check-in</div><div class="title">Readiness snapshot</div>${renderCoachCheckin()}</section><section class="card"><div class="eyebrow">Programming</div><div class="title">Assigned week</div>${CLIENT.workouts.map(w=>`<div class="row"><span class="label">${esc(w.day)} · ${esc(w.name)}</span><span class="value">${esc(w.focus)}</span></div>`).join('')}</section></section><aside class="grid"><section class="card"><div class="eyebrow">Client record</div><div class="coach-client"><div class="avatar">A</div><div><div style="font-weight:700;font-size:13px">${esc(CLIENT.name)}</div><div class="sub">Active · Week ${CLIENT.week} of ${CLIENT.programWeeks}</div></div></div><div class="list" style="margin-top:12px"><div class="row"><span class="label">Goals</span><span class="value">${CLIENT.goals.join(' · ')}</span></div><div class="row"><span class="label">Cycle tracking</span><span class="value">Configurable</span></div><div class="row"><span class="label">Private files</span><span class="value">Supabase Storage</span></div></div></section><section class="card"><div class="eyebrow">Coach notes</div><div class="list">${state.notes.slice().reverse().map(n=>`<div class="row"><span class="label">${esc(n.text)}</span><span class="value">${fmtDate(n.date)}</span></div>`).join('')||'<div class="empty">No notes yet.</div>'}</div></section></aside></div>`}
function renderCoachCheckin(){const c=state.checkins[today()];if(!c)return '<div class="empty">No check-in today yet.</div>';return `<div class="list"><div class="row"><span class="label">Day type</span><span class="value">${esc(c.dayType||'—')}</span></div>${CLIENT.checkin.items.map(([k,a])=>`<div class="row"><span class="label">${esc(a)}</span><span class="value">${c.items?.[k]?'✓':'—'}</span></div>`).join('')}${c.flag?`<div class="notice">Flag: ${esc(c.flag)}</div>`:''}</div>`}
function bindCoach(){document.getElementById('editProgram')?.addEventListener('click',()=>openModal(`<div class="modal-head"><div><div class="eyebrow">Client programming</div><div class="title">Edit ${esc(CLIENT.name)}</div></div><button class="close" onclick="closeModal()">×</button></div><p class="sub">This v1 screen demonstrates the reusable architecture. The next schema-backed Coach Hub will save these assignments to Supabase instead of hard-coding them.</p><div class="list" style="margin-top:14px">${Object.entries(CLIENT.schedule).map(([d,v])=>`<div class="row"><span class="label">${d}</span><span class="value">${esc(v.focus)}</span></div>`).join('')}</div>`));document.getElementById('coachNote')?.addEventListener('click',()=>openModal(`<div class="modal-head"><div><div class="eyebrow">Private note</div><div class="title">Add coach note</div></div><button class="close" onclick="closeModal()">×</button></div><textarea class="input textarea" id="modalNote" placeholder="What should be remembered for this client?"></textarea><button class="btn" style="margin-top:10px" onclick="saveModalNote()">Save note</button>`))}
function openModal(html){const m=document.getElementById('modal');m.innerHTML=`<div class="modal">${html}</div>`;m.classList.add('open');m.setAttribute('aria-hidden','false')}
function closeModal(){const m=document.getElementById('modal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
window.closeModal=closeModal;window.saveModalNote=()=>{const text=document.getElementById('modalNote').value.trim();if(text){state.notes.push({date:today(),text});persist();closeModal();toast('Coach note saved');showMode('coach')}};
async function loadClientWorkouts(){

const {data,error}=await sb
.from('client_workouts')
.select(`
id,
name,
scheduled_date,
client_workout_exercises(
sort_order,
exercises(name)
)
`)
.eq('client_id','d671af58-2ca1-42a6-b898-ccf5b9c91461');

if(error){
console.error(error);
return;
}

CLIENT.workouts=data.map(w=>({
id:w.id,
day:'',
name:w.name,
focus:'Assigned workout',
note:'',
exercises:(w.client_workout_exercises||[])
.sort((a,b)=>a.sort_order-b.sort_order)
.map(e=>({
name:e.exercises.name
}))
}));

}
initAuth();
loadClientWorkouts().then(()=>render());
